spring:
  application:
    name: LiveScore
  jpa:
    properties:
      hibernate:
        format_sql=true:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

live-score:
  source-url: http://static.cricinfo.com/rss/livescores.xml