server:
  port: 8080

spring:
  application:
    name: LiveScore
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/live_score?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true

live-score:
  source-url: http://static.cricinfo.com/rss/livescores.xml
  jwt:
    secret: 5QVmYq3t6w9z$C&F)J@Mc%fTjWnZr4u7x!A%D*G-KaPdRgUkXp2s5v8y/B?E(H+Mb
    expiration: 86400